"""Phase 2 Domain Entities

Revision ID: 0fe27df1ed94
Revises: 
Create Date: 2026-09-14 05:40:46.402879
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe27df1ed94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE', 'ARCHIVED')", name='habitats_state_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE', 'ARCHIVED')", name='users_state_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE', 'ARCHIVED')", name='ai_identities_state_check'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habitat_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('habitat_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('OWNER', 'MEMBER')", name='habitat_memberships_role_check'),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'habitat_id', name='uq_habitat_memberships_user_habitat')
    )
    op.create_table('habitat_participations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_identity_id', sa.Uuid(), nullable=False),
    sa.Column('habitat_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE', 'ARCHIVED')", name='habitat_participations_state_check'),
    sa.ForeignKeyConstraint(['ai_identity_id'], ['ai_identities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_identity_id', 'habitat_id', name='uq_habitat_participations_ai_habitat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habitat_participations')
    op.drop_table('habitat_memberships')
    op.drop_table('ai_identities')
    op.drop_table('users')
    op.drop_table('habitats')
    # ### end Alembic commands ###
